# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.SmallIntegerField()),
                ('humidity', models.SmallIntegerField()),
                ('heater', models.SmallIntegerField()),
                ('vent', models.SmallIntegerField()),
                ('fan', models.SmallIntegerField()),
            ],
        ),
    ]
